#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include "auxFuncs.h"
#include "nodes.h"
#include "comparator.h"
#include "hasher.h"
#include "cmdstruct.h"
#include "doublelist.h"
#include "doublelistcomp.h"
#include "stackList.h"
#include "queueList.h"
#include "BST.h"
#include "hashtable.h"
#include "hashtablecomp.h"
#include "hashtablecmd.h"
#include "minHeap.h"
#include "../cmdModules/Includes/cmdds.h"
#include "../cmdModules/Includes/cmdfuncexmpl.h"
#include "../cmdModules/Includes/cmdsbst.h"
#include "../cmdModules/Includes/cmdsdlist.h"
#include "../cmdModules/Includes/cmdshashtable.h"
#include "../cmdModules/Includes/cmdsqueue.h"
#include "../cmdModules/Includes/cmdsstack.h"
